import random
cities = [
    "mumbai",
    "delhi",
    "bangalore",
    "hyderabad",
    "ahmedabad",
    "chennai",
    "kolkata",
    "surat",
    "pune",
    "jaipur",
    "lucknow",
    "kanpur",
    "nagpur",
    "visakhapatnam",
    "indore",
    "thane",
    "bhopal",
    "patna",
    "vadodara",
    "ghaziabad",
    "ludhiana",
    "coimbatore",
    "agra",
    "madurai",
    "nashik",
    "faridabad",
    "meerut",
    "rajkot",
    "kalyan-dombivali",
    "vasai-virar",
    "varanasi",
    "srinagar",
    "aurangabad",
    "dhanbad",
    "amritsar",
    "navi mumbai",
    "allahabad",
    "howrah",
    "ranchi",
    "gwalior",
    "jabalpur",
    "jodhpur",
    "raipur",
    "kota",
    "guwahati",
    "chandigarh",
    "solapur",
    "hubli-dharwad",
    "bareilly",
    "moradabad",
    "mysore",
    "gurgaon",
    "aligarh",
    "jalandhar",
    "tiruchirappalli",
    "bhubaneswar",
    "salem",
    "mira-bhayandar",
    "warangal",
    "thiruvananthapuram",
    "guntur",
    "bhiwandi",
    "saharanpur",
    "gorakhpur",
    "bikaner",
    "amravati",
    "noida",
    "jamshedpur",
    "bhilai",
    "cuttack",
    "kochi",
    "uzhno-sakhalinsk",
    "khabarovsk",
    "vancouver",
    "victoria",
    "abbotsford",
    "kelowna",
    "nanaimo",
    "kamloops",
    "prince george",
    "chilliwack"
    "nyc",
    "la",
    "chicago",
    "houston",
    "phoenix",
    "philadelphia",
    "san antonio",
    "san diego",
    "dallas",
    "san jose",
    "austin",
    "jacksonville",
    "san francisco",
    "columbus",
    "fort worth",
    "indianapolis",
    "charlotte",
    "seattle",
    "denver",
    "washington",
    "boston",
    "el paso",
    "detroit",
    "nashville",
    "memphis",
    "portland",
    "oklahoma city",
    "las vegas",
    "louisville",
    "baltimore",
    "milwaukee",
    "albuquerque",
    "tucson",
    "fresno",
    "sacramento",
    "mesa",
    "kansas city",
    "atlanta",
    "long beach",
    "colorado springs",
    "raleigh",
    "miami",
    "virginia beach",
    "omaha",
    "oakland",
    "minneapolis",
    "tulsa",
    "arlington",
    "new orleans",
    "wichita",
    "cleveland",
    "tampa",
    "bakersfield",
    "aurora",
    "honolulu",
    "anaheim",
    "santa ana",
    "corpus christi",
    "riverside",
    "lexington",
    "stockton",
    "pittsburgh",
    "st. paul",
    "anchorage",
    "cincinnati",
    "henderson",
    "greensboro",
    "plano",
    "newark",
    "toledo",
    "lincoln",
    "orlando",
    "chula vista",
    "irvine",
    "fort wayne",
    "jersey city",
    "durham",
    "st. petersburg",
    "laredo",
    "buffalo",
    "madison",
    "lubbock",
    "chandler",
    "scottsdale",
    "glendale",
    "reno",
    "norfolk",
    "winston-salem",
    "north las vegas",
    "irving",
    "chesapeake",
    "gilbert",
    "hialeah",
    "garland",
    "fremont",
    "baton rouge",
    "richmond",
    "boise",
    "san bernardino",
    "spokane",
    "birmingham",
    "modesto",
    "des moines",
    "rochester",
    "tacoma",
    "fontana",
    "oceanside",
    "mobile",
    "vancouver",
    "victoria",
    "abbotsford",
    "kelowna",
    "nanaimo",
    "kamloops",
    "dublin",
    "cork",
    "limerick",
    "galway",
    "waterford",
    "drogheda",
    "dundalk",
    "derry",
    "belfast",
    "lisburn",
    "newtownabbey",
    "bangor",
    "craigavon",
    "castlereagh",
    "ballymena",
    "newtownards",
    "coleraine",
    "omagh",
    "tokyo",
    "yokohama",
    "osaka",
    "nagoya",
    "sapporo",
    "kobe",
    "kyoto",
    "fukuoka",
    "kawasaki",
    "saitama",
    "hiroshima",
    "sendai",
    "kitakyushu",
    "chiba",
    "sakai",
    "niigata",
    "hamamatsu",
    "sagamihara",
    "okayama",
    "kumamoto",
    "kanazawa",
    "nara",
    "kagoshima",
    "kochi",
    "akita",
    "aomori",
    "morioka",
    "fukushima",
    "yamagata",
    "nagano",
    "niigata",
    "shizuoka",
    "hamamatsu",
    "gifu",
    "shizuoka",
    "dubai",
    "abu dhabi",
    "sharjah",
    "al ain",
    "ajman",
    "ras al khaimah",
    "um al quwain",
    "khor fakkan",
    "kalba",
    "dibba al-fujairah",
    "madrid",
    "barcelona",
    "valencia",
    "seville",
    "zaragoza",
    "málaga",
    "murcia",
    "palma",
    "las palmas",
    "bilbao",
    "alicante",
    "córdoba",
    "valladolid",
    "vigo",
    "gijón",
    "hospitalet",
    "la coruña",
    "granada",
    "vitoria",
    "elche",
    "oviedo",]
file_name= "weather_stations.csv"
row_count = 1_000_000_000
min_temp = -50
max_temp = 50

with open(file_name, mode='w', encoding="UTF-8") as file:
    for i in range(row_count):
        file.write(f"{cities[i%len(cities)]};{random.randrange(min_temp, max_temp)}\n")
        if i%1000000 == 0:
            print(f"{i} rows written")

print(f"Data generation complete. {row_count} rows written to {file_name}")
input("Press Enter to exit")